---
title: "FigS10"
author: "Jixing Zhong"
date: "2/18/2023"
output: html_document
---

```{r}
library(Seurat)
library(dplyr)
library(ggplot2)
library(ComplexHeatmap)
library(RColorBrewer)
library(patchwork)
#remotes::install_github('jorvlan/raincloudplots')
library(raincloudplots)
source("/Users/jzhong/Desktop/Desktop–SV-96M-002/EPFL/project/axolotl_aer_final/rmd_pl_figs/0.scripts/R_rainclouds.R")

options(ggplot2.discrete.colour = "#E78AC3")
options(ggplot2.discrete.fill = "#E78AC3")

p_theme <- function() {
    theme_bw() %+replace%
        theme(
            legend.position = "none",
            axis.title.y = element_blank(),
            axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1),
            axis.title.x = element_blank(),
            plot.title = element_text(hjust = 0.5, face = "bold")
        )
}
```

```{r}
df <- readRDS('/Users/jzhong/Desktop/Desktop–SV-96M-002/EPFL/project/axolotl_aer_final/rmd_pl_figs/separate_metadata_reg.rds')
df <- df[df$orig.ident == 'Frog_reg',]

CellNum <- data.frame(id = 'Frog_reg', CellNum = nrow(df))

```


```{r, fig.width=10, fig.height=4}
p_cell <- ggplot(CellNum, aes(id, CellNum, fill = id)) +
    geom_bar(stat = "identity") +
    ggtitle("Cell Numbers") +
    p_theme()

p_umi <- ggplot(df, aes(x = old.ident, y = nCount_RNA, fill = orig.ident)) +
    geom_flat_violin(
        position = position_nudge(x = 0, y = 0),
        adjust = 2, trim = TRUE, scale = "width", color = NA, alpha = 0.7
    ) +
    geom_boxplot(
        position = position_nudge(x = -.2, y = 0),
        outlier.shape = NA, width = .2, lwd = .2,
    ) +
    ggtitle("Transcript numbers per cell") +
    p_theme()

p_gene <- ggplot(df, aes(x = old.ident, y = nFeature_RNA, fill = orig.ident)) +
    geom_flat_violin(
        position = position_nudge(x = 0, y = 0),
        adjust = 2, trim = TRUE, scale = "width", color = NA, alpha = 0.7
    ) +
    geom_boxplot(
        position = position_nudge(x = -.2, y = 0),
        outlier.shape = NA, width = .2, lwd = .2,
    ) +
    ggtitle("Gene numbers per cell") +
    p_theme()

p_mito <- ggplot(df, aes(x = old.ident, y = percent.mt, fill = orig.ident)) +
    geom_flat_violin(
        position = position_nudge(x = 0, y = 0),
        adjust = 2, trim = TRUE, scale = "width", color = NA, alpha = 0.7
    ) +
    geom_boxplot(
        position = position_nudge(x = -.2, y = 0),
        outlier.shape = NA, width = .2, lwd = .2,
    ) +
    ggtitle("Percentage of mitochodrial genes per cell") +
    p_theme()


wrap_plots(p_cell, p_umi, p_gene, p_mito, nrow = 1)

```


```{r}
cols2 <- c(
    brewer.pal(12, "Paired")[c(1:6, 8:10)],
    "#F0027F", "lightgrey"
)
names(cols2) <- c("CT","BasalEctoderm","Muscle","Blood","Immune","Endo",
                  "Goblet","DiffEctoderm","Pericyte","AER","Unknown" )

ggplot(df, aes(UMAP_1, UMAP_2, color = CellType2)) + geom_point(size = .3) + 
  theme_classic() + scale_color_manual(values = cols2)

```


```{r,, fig.width=15}
mat <- readRDS('supp_heatmap.rds')

ha <- HeatmapAnnotation(
  CellType2 = df$CellType2[match(colnames(mat), rownames(df))],
  col = list(CellType2 = cols2),
  show_legend = FALSE
)

Heatmap(mat,
  name = 'Expression',
  show_column_names = FALSE,
  row_names_side = 'left',
  # row_labels = gsub('\\.[0-9]+', '', rownames(mat)),
  
  column_split = factor(
    df$CellType2[match(colnames(mat), rownames(df))],
    levels = c(
      'CT',
      'BasalEctoderm',
      'AER',
      'DiffEctoderm',
      'Goblet',
      'Muscle',
      'Blood',
      'Immune',
      'Endo',
      "Pericyte"
    )
  ),
  top_annotation = ha,
  
  cluster_rows = FALSE,
  cluster_columns = FALSE,
  
  col = circlize::colorRamp2(c(-2, 0, 2), c("#67a9cf", "white", "#b2182b")),
  use_raster = TRUE,
)

```

```{r, fig.height=8}
load('FigS10_supp.rdata')
source('../0.scripts/dotplot_fromTOM.r')

dotplot(countn,
    norm = "max",
    conditionList = c("Frog_NF50" ,"Frog_NF51" ,"Frog_NF52" ,"Frog_NF54","Frog_reg"),
    condition = condition,
    title = "Signaling ligands in AER/AEC",
    collow = "lightgrey", colhigh = "red3",
    aspect.ratio = 4, ySize = 8, xSize = 8, dot.scale = 3,
    return = TRUE, plot = FALSE
)

```

