---
title: "FigS8"
author: "Jixing Zhong"
date: "2/18/2023"
output: html_document
---


```{r}
library(ggplot2)
library(patchwork)
library(ggtext)
source("../0.scripts/dot_plot_combine_sp.r")
```

```{r}
total_mat <- readRDS('../Fig1/supp_dotplot.rds')
gene2pathway <- readRDS('../gene2pathway.rds')
```

```{r, fig.width=15, fig.height=8}
p_list <- lapply(unique(gene2pathway)[1:5], function(i){
   genes <- names(gene2pathway)[gene2pathway == i]
    total_mat_sub <- subset(total_mat, features.plot %in% genes)

    idx <- stringr::str_order(unique(total_mat_sub$features.plot), numeric = TRUE)
    total_mat_sub$features.plot <- factor(total_mat_sub$features.plot,
        levels = unique(total_mat_sub$features.plot)[idx]
    )
    p <- dot_plot(total_mat = total_mat_sub, x = features.plot, y = id2) +
        theme(axis.text.y = element_markdown())

    p <- p + labs(title = i)
}) 
   

lay <- '
BBEE
AACD'
wrap_plots(p_list, design = lay, guides = 'collect') +
    scale_size_continuous(limits = range(0, 100))

```

